evmNetworkId: 100
priceMultiplier: 1
issueCreatorMultiplier: 2
paymentPermitMaxPrice: 9007199254740991
maxConcurrentAssigns: 9007199254740991
assistivePricing: false
disableAnalytics: false
commentIncentives: false
registerWalletWithVerification: false
promotionComment: "\n<h6>If you enjoy the DevPool experience, please follow <a href='https://github.com/ubiquity'>Ubiquity on GitHub</a> and star <a href='https://github.com/ubiquity/devpool-directory'>this repo</a> to show your support. It helps a lot!</h6>"
defaultLabels: []
timeLabels: 
  - "Time: <1 Hour"
  - "Time: <2 Hours"
  - "Time: <4 Hours"
  - "Time: <1 Day"
  - "Time: <1 Week"
priorityLabels: 
  - "Priority: 1 (Normal)"
  - "Priority: 2 (Medium)"
  - "Priority: 3 (High)"
  - "Priority: 4 (Urgent)"
    "Priority: 5 (Emergency)"
commandSettings:
   - name: "start"
     enabled: true
   - name: "help"
     enabled: true
   - name: "stop"
     enabled: false
   - name: "wallet"
     enabled: true
   - name: "payout"
     enabled: false
   - name: "multiplier"
     enabled: false
   - name: "query"
     enabled: false
   - name: "ask"
     enabled: false
   - name: "allow"
     enabled: false
   - name: "autopay"
     enabled: false
incentives: 
  comment: 
    elements: 
      code: 1
      img: 0
      h1: 1
      h2: 1
      h3: 1
      h4: 1
      h5: 1
      h6: 1
      li: 0.5
      a: 1
      blockquote: 0
      i: 0
    totals: 
      character: 1
      word: 1
      sentence: 1
      paragraph: 1
      comment: 1
      
  enableAccessControl: 
    label: false
    organization: true
 
  staleBountyTime: "0d"
  timeRangeForMaxIssue: 24
  timeRangeForMaxIssueEnabled: false
  permitBaseUrl: "https://pay.ubq.fi"
  botDelay: 100
  followUpTime: "4 days"
  disqualifyTime: "7 days"
  newContributorGreeting: 
    enabled: true
    header: "Thank you for contributing to UbiquiBot! Please be sure to set your wallet address before completing your first bounty so that the automatic payout upon task completion will work for you."
    helpMenu: true
    footer: "###### Also please star this repository and [@ubiquity/devpool-directory](https://github.com/ubiquity/devpool-directory/) to show your support. It helps a lot!"
