evmNetworkId: 100
issueCreatorMultiplier: 1
timeLabels:
  - name: "Time: <1 Hour"
  - name: "Time: <2 Hours"
  - name: "Time: <4 Hours"
  - name: "Time: <1 Day"
  - name: "Time: <1 Week"
priorityLabels:
  - name: "Priority: 1 (Normal)"
  - name: "Priority: 2 (Medium)"
  - name: "Priority: 3 (High)"
  - name: "Priority: 4 (Urgent)"
  - name: "Priority: 5 (Emergency)"
defaultLabels:
  - "Time: <1 Hour"
  - "Priority: 1 (Normal)"
paymentPermitMaxPrice: 1000
commentIncentives: true
maxConcurrentAssigns: 5
promotionComment: ""
assistivePricing: true
registerWalletWithVerification: false
commandSettings:
  - name: start
    enabled: true
  - name: stop
    enabled: true
  - name: wallet
    enabled: true
  - name: multiplier
    enabled: true
  - name: query
    enabled: true
  - name: autopay
    enabled: true
  - name: agent
    enabled: true
  - name: allow
    enabled: true
  - name: help
    enabled: true
  - name: payout
    enabled: true
  - name: ask
    enabled: true
  - name: config
    enabled: true
disableAnalytics: false
enableAccessControl:
  label: true
  organization: true
incentives:
  comment:
    elements:
      code: 5
      img: 5
      h1: 1
      li: 0.5
      a: 0.5
      blockquote: 0
    totals:
      word: 0.1
