export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function DualLayout(props: {
  children: React.ReactNode;
  data: React.ReactNode;
  docs: React.ReactNode;
}) {
  return (
    <div className="">
      {""}
      {""}
    </div>
  );
}
